lg/urls.py
from django.urls import path, reverse_lazy

from . import views


app_name = "lg"


urlpatterns = [


	path('', views.index, name="index" ),

	path('2/', views.index2, name="index2" ),
	path('3/', views.index3, name="index3" ),


	path('campaign/', views.campaign_view, name="campaign_view" ),






	path("api/campaign_list/", views.campaign_list, name="campaign_list"),

	path("api/select_list/<str:type>", views.select_list, name="select_list"),
	#path("api/select_list/<str:type>", views.select_list.as_view(), name="select_list"),



	path('home/', views.HomeView.as_view(), name="home" ),

	path("api/todo/list", views.ApiTodoLV.as_view(), name="list"),




]

pybo/urls.py
from django.urls import path, reverse_lazy

from .views import base_views, question_views, answer_views, comment_views, vote_views, q_views

from django.views.generic import CreateView
from pybo.models import Question, Todo






app_name = "pybo"

urlpatterns = [



    path('q_list/', q_views.q_list,name="q_list" ),




    path('api/', base_views.apiOverview,name="api-overview" ),


    path('q-list/', base_views.questionList,name="question-list" ),
    path('q-detail/<str:pk>/', base_views.questionDetail,name="question-detail" ),

    path('q-create/', base_views.questionCreate,name="question-create" ),

    path('t-list/', base_views.todoList,name="todo-list" ),
    path('t-create/', base_views.todoCreate,name="todo-create" ),

    path('t-update/<str:pk>/', base_views.todoUpdate,name="todo-update" ),
    path('t-delete/<str:pk>/', base_views.todoDelete,name="todo-delete" ),















    # path("home/", CreateView.as_view(model=Todo, fields=['title'], success_url=reverse_lazy('home')), name="home"),

    path("hssome/", base_views.TodoCreateView.as_view(), name="home"),




















    path("", base_views.index, name='index'),
    path("<int:question_id>/", base_views.detail, name="detail"),

    path("question/create/", question_views.question_create, name="question_create"),
    path("question/modify/<int:question_id>/", question_views.question_modify, name="question_modify"),
    path("question/delete/<int:question_id>/", question_views.question_delete, name="question_delete"),

    path("answer/create/<int:question_id>/", answer_views.answer_create, name="answer_create"),
    path("answer/modify/<int:answer_id>/", answer_views.answer_modify, name="answer_modify"),
    path("answer/delete/<int:answer_id>/", answer_views.answer_delete, name="answer_delete"),

    path("comment/create/question/<int:question_id>/", comment_views.comment_create_question, name="comment_create_question"),
    path("comment/modify/question/<int:comment_id>/", comment_views.comment_modify_question, name="comment_modify_question"),
    path("comment/delete/question/<int:comment_id>/", comment_views.comment_delete_question, name="comment_delete_question"),
    path("comment/create/answer/<int:answer_id>", comment_views.comment_create_answer, name="comment_create_answer"),
    path("comment/modify/answer/<int:comment_id>", comment_views.comment_modify_answer, name="comment_modify_answer"),
    path("comment/delete/answer/<int:comment_id>", comment_views.comment_delete_answer, name="comment_delete_answer"),



    path("vote/question/<int:question_id>/", vote_views.vote_question, name="vote_question"),
    path("vote/answer/<int:answer_id>", vote_views.vote_answer, name="vote_answer"),



    path("about/", question_views.AboutView.as_view(), name="about"),





    path("hresponse//", question_views.hresponse_view, name="hresponse"),
    path("reverse/<int:question_id>", question_views.reverse_view, name="reverse"),
    path("resolve_url/<int:question_id>", question_views.resolveurl_view, name="resolveurl_view"),
    path("redirect_view/<int:question_id>", question_views.redirect_view, name="redirect_view"),
    path("reverse_lazy/<int:question_id>", question_views.reverselazy_view, name="reverselazy_view"),
    path("resol/<int:question_id>", question_views.resolve_view, name="resolve_view"),



]

pybo/models.py
from django.db import models

from django.contrib.auth.models import User

from django.shortcuts import reverse


class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()    
    modify_date = models.DateTimeField(null=True,blank=True)


    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    voter = models.ManyToManyField(User, related_name='voter_question')

    # 추천자야.
    
    def __str__(self):
        return self.subject

    def get_absolute_url(self):
        return reverse('pybo:detail', args=[self.id])
        


class Answer(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True,blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')

    voter = models.ManyToManyField(User, related_name='voter_answer')


class Comment(models.Model):
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True,blank=True)
    answer = models.ForeignKey(Answer,null=True,blank=True,on_delete=models.CASCADE)
    question = models.ForeignKey(Question,null=True,blank=True,on_delete=models.CASCADE)
    
    # 아..구동방식이. type이 아니라, 클래스유무로 가린다


class Todo(models.Model):
    title = models.CharField(max_length=256)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title





class Department(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
class Employee(models.Model):
    name = models.CharField(max_length=124)
    age = models.IntegerField()
    department = models.ForeignKey(Department, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
        














class Book(models.Model):
    name = models.CharField(max_length=300)
    price = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class Store(models.Model):
    name = models.CharField(max_length=300)
    books = models.ManyToManyField(Book)

    def __str__(self):
        return self.name



    





        
    
    

pybo/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect,resolve_url
from django.utils import timezone

from ..forms import AnswerForm
from ..models import Question, Answer

from util import *



@login_required(login_url="common:login")

def answer_create(request, question_id):
	question = get_object_or_404(Question,pk=question_id)
	if request.method == "POST":
		form = AnswerForm(request.POST)
		if form.is_valid():


			# question.answer_set.create(
			# 	content = request.POST.get('content'),
			# 	create_date = timezone.now(),
			# 	author = request.user
			# )

			answer = form.save(commit=False)
			answer.author = request.user
			answer.create_date = timezone.now()
			answer.question = question
			answer.save()

			return redirect("{}#answer_{}".format(
				resolve_url('pybo:detail',question_id=question.id),
				answer.id
			))



	else:
		form = AnswerForm()
		context = {'form':form}
	return render(request,'pybo/detail.html',context)































	
	
	
	
@login_required(login_url="common:login")
	
def answer_modify(request,answer_id):
	answer = get_object_or_404(Answer,pk=answer_id)
	if request.method == "POST":
		form = AnswerForm(request.POST,instance= answer)
		if form.is_valid():
			answer = form.save(commit=False)
			answer.author = request.user
			answer.modify_date = timezone.now()
			answer.save()
			
			# print("DONE : anser :")
			# pprint(vars(answer.question))

			print("modify works")

			return redirect("{}#answer_{}".format(
				resolve_url('pybo:detail',question_id = answer.question.id),
				answer.id
			))
			
			
	else:
		form = AnswerForm(instance=answer)
	context = {'form':form}
	return render(request,'pybo/answer_form.html',context)
	
	
	
	
	
@login_required(login_url="common:login")

def answer_delete(request,answer_id):
	answer = get_object_or_404(Answer,pk=answer_id)
	if answer.author != request.user:
		print("you wrong user. you are hacker?")
	
	else:
		answer.delete()
		print("delete done .. lol !")
	return redirect("pybo:detail",question_id= answer.question.id)

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.shortcuts import render, get_object_or_404, redirect, reverse, resolve_url


from ..models import Question,Book,Store,Employee,Department

# from util import *


# def index(request):

# 	print("LIST WORKS")

# 	print("okay helloworld")
# 	print(Question.objects.filter(subject__contains="sO"))

# 	page = request.GET.get('page','1')
# 	question_list = Question.objects.order_by('-create_date')
# 	paginator = Paginator(question_list,20)
# 	page_obj = paginator.get_page(page)
# 	context = {'question_list':page_obj}

# 	return render(request,'pybo/question_list.html',context)






from django.db.models import Q, Count



import logging

logger = logging.getLogger('pybo')

print(">>>")
print(__name__)
# pybo는.. 로거명이다.
# 이걸로 logger.debug, logger.error, logger.warning

# 이 로거 객체는.. 이제 이걸로 info,warning,error,debug 메소드를 쓸 수 있다..!
'''
def index(request):

	# logger.info("INFO 레벨로 출력한다!")
	# logger.warning("warning 레벨로 출력한다!")
	# logger.error("error 레벨로 출력한다!")
	# logger.debug("debug 레벨로 출력한다!")
	
	page = request.GET.get('page',1)
	kw = request.GET.get('kw','')
	so = request.GET.get('so','recent')

	if so == "recommend":
		question_list = Question.objects.annotate(
			r_count = Count('voter'),
			cr_count = Count('voter'),
		).order_by('-r_count','-create_date').distinct()



	elif so == "question":
		question_list = Question.objects.annotate(
			q_count = Count('answer')
		).order_by('-q_count','-create_date').distict()
	else:
		question_list = Question.objects.order_by('-create_date')


	if kw:
		question_list = question_list.filter(
			Q(subject__icontains = kw) |
			Q(content__icontains = kw) |
			Q(author__username__icontains = kw) |
			Q(answer__author__username__icontains = kw)
		)


	paginator = Paginator(question_list,15)
	page_obj = paginator.get_page(page)

	context = {'question_list':page_obj, 'page':page,'kw':kw,'so':so}
	return render(request,'pybo/question_list.html',context)
'''











minusfunc = lambda a,b : a-b


def detail(request, question_id):

	print("hello im detail")
	question = get_object_or_404(Question, pk=question_id)
	context = {"question": question}

	print("--work--")

	# resolve_url은 reverse고.. reverse에서 args=[self.id] 를 간략화한 버전이다!
	# print( resolve_url('pybo:detail', question_id) )
	
	# print( resolve_url(question) )
	# print( redirect(question) )

	# 사실 resolve_url이 필요한건.. 맨 뒤 name이다.!


	return render(request, "pybo/question_detail.html", context)



from django.views.generic import CreateView
from pybo.models import Todo
from django.urls import reverse_lazy
from pybo.forms import TodoForm



from django.http import JsonResponse
from rest_framework.decorators import api_view
from rest_framework.response import Response
from ..serializers import QuestionSerializer, TodoSerializer 


@api_view(['GET'])
def apiOverview(request):
	api_urls = {'sucks':'sucks'}
	return Response(api_urls)
	

@api_view(['GET'])
def questionList(request):
	questions = Question.objects.all()
	serializer = QuestionSerializer(questions, many=True)
	return Response(serializer.data)
	
@api_view(['GET'])
def todoList(request):
	todos = Todo.objects.all()
	serializer = TodoSerializer(todos, many=True)
	return Response(serializer.data)



@api_view(['GET'])
def questionDetail(request,pk):
	questions = Question.objects.get(id=pk)
	serializer = QuestionSerializer(questions, many=False)
	return Response(serializer.data)

@api_view(['POST'])
#THIS only allow POST
def questionCreate(request):
	serializer = QuestionSerializer(data = request.data)
	if serializer.is_valid():
		serializer.save()
	return Response(serializer.data)




@api_view(['POST'])
def todoCreate(request):
	serializer = TodoSerializer(data = request.data)
	if serializer.is_valid():
		serializer.save()
	return Response(serializer.data)
	

@api_view(['POST'])
def todoUpdate(request, pk):
	todo = Todo.objects.get(id=pk)
	serializer = TodoSerializer(instance = todo, data = request.data)
	if serializer.is_valid():
		serializer.save()
	return Response(serializer.data)
	



@api_view(['DELETE'])
def todoDelete(request, pk):
	todo = Todo.objects.get(id=pk)
	todo.delete()
	return Response("your data is fucked! okay!")
	#ah.. Response는 아예 그 template를 만들어줌 











class TodoCreateView(CreateView):
	model = Todo
	# fields = '__all__'
	form_class = TodoForm
	success_url = reverse_lazy('pybo:home')

	# template_name = 'pybo/todo_former.html'
	template_name_suffix = '_create_form'

	def get_context_data(self,**kwargs):
		context = super(TodoCreateView,self).get_context_data(**kwargs)
		
		context['todos'] = Todo.objects.all()

		# 보면 context호출시 모든..todo가 호출되고 있다..!

		return context

	# def form_invalid(self, form):
	# 	print("invalid..stop!")

	def form_valid(self,form):
		print("valid.. proceed")
		return super().form_valid(form)


from django.http import HttpResponse
from django.views import View

class MyView(View):

    def get(self, request, *args, **kwargs):
        return HttpResponse('Hello, World! IM GET!')

    def POST(self, request, *args, **kwargs):
        return HttpResponse('Hello, World! IM POST!')

pybo/views/comment_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import CommentForm
from ..models import Question, Answer, Comment







@login_required(login_url="common:login")
def comment_create_question(request,question_id):
	question = get_object_or_404(Question,pk=question_id)
	if request.method=="POST":
		form = CommentForm(request.POST)
		if form.is_valid():
			comment = form.save(commit=False)
			comment.question = question
			comment.author = request.user
			comment.create_date = timezone.now()
			comment.save()

			return redirect("{}#comment_{}".format(
					resolve_url('pybo:detail',question_id=question.id),
					comment.id
			))

	else:
		form = CommentForm()
		
	context = {'form':form}
	return render(request,'pybo/comment_form.html',context)





















@login_required(login_url="common:login")
def comment_modify_question(request,comment_id):
	comment = get_object_or_404(Comment,pk=comment_id)
	if request.method == "POST":
		form = CommentForm(request.POST, instance=comment)
		if form.is_valid():
			comment = form.save(commit=False)
			comment.author = request.user
			comment.modify_date = timezone.now()
			comment.save()

			print("cmt / question / edit works")
			return redirect("{}#comment_{}".format(
				resolve_url('pybo:detail',question_id=comment.question.id),
				comment.id
			))


	else:
		form = CommentForm(instance = comment)
	context ={'form':form}

	return render(request,'pybo/comment_form.html',context)

	  



@login_required(login_url="common:login")
def comment_delete_question(request,comment_id):
	comment = get_object_or_404(Comment,pk=comment_id)
	if comment.author != request.user:
		print("CANNOT DELETE")
	else:
		comment.delete()
	print("EVERYTHING IS OKAY,BUT HOW TO GET DELTED DATA?")
	print(comment.question)
	print(comment.question.id)
	return redirect("pybo:detail" , question_id = comment.question.id)














@login_required(login_url="common:login")
def comment_create_answer(request,answer_id):
	answer = get_object_or_404(Answer,pk=answer_id)
	if request.method == "POST":
		form = CommentForm(request.POST)
		if form.is_valid():
			comment = form.save(commit=False)
			comment.answer = answer
			comment.author = request.user
			comment.create_date = timezone.now()
			comment.save()

			return redirect("{}#comment_{}".format(
				resolve_url('pybo:detail',question_id = comment.answer.question.id),
				comment.id
			))

	else:
		form = CommentForm()
	context = {'form':form}
	return render(request,'pybo/comment_form.html',context)












@login_required(login_url="common:login")
def comment_modify_answer(request, comment_id):
	comment = get_object_or_404(Comment,pk=comment_id)
	if request.method == "POST":
		form = CommentForm(request.POST, instance=comment)
		if form.is_valid():
			comment = form.save(commit=False)
			comment.modify_date = timezone.now()
			comment.save()

			return redirect("{}#comment_{}".format(
				resolve_url("pybo:detail",question_id=comment.answer.question.id),
				comment.id
			))

	else:
		form = CommentForm(instance=comment)
	context = {'form':form}
	return render(request,'pybo/comment_form.html',context)		
	



@login_required(login_url="common:login")
def comment_delete_answer(request,comment_id):
	comment = get_object_or_404(Comment,pk=comment_id)
	if request.user != comment.author:
		print("you cannot DELETE HIM")
	else:
		comment.delete()
	return redirect("pybo:detail", question_id = comment.answer.question.id)
	

templates/pybo/about.html
IM ABOUT!

templates/pybo/answer_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <form method="post" class="post-form">
        {% csrf_token %}
        <div class="form-group">
            <label for="content">답변내용</label>
            <textarea class="form-control" name="content" id="content" 
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/book.html
bookview!

templates/pybo/comment_form.html
{% extends 'base.html' %}



{% block content %}
        HELLO IM FORM OF COMMENT!

        <form method="POST">
            {% csrf_token %}

            {{form.as_p}}

                    
            <input type="submit" value="전송">
        </form>



{% endblock %}
    

templates/pybo/q_list.html
<html>
<body>
	lol!
	
















	
</body>
</html>

templates/pybo/question_detail.html
{% extends 'base.html' %}

{% load pybo_filter %}


{% block content %}

<script>
    if ( window.history.replaceState ) {
    window.history.replaceState( null, null, window.location.href );
      }
</script>

<div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <h5>{{ question.author }}</h5>

    <div>이 유저가 추천한 질문 게시물임다<b>(user.voter_question.all)</b> : <br>{{user.voter_question.all}}</div>
    <div>이 유저가 추천한 답변 게시물임다<b>(user.voter_answer.all)</b> <br> : {{user.voter_answer.all}}</div>
    <div>이 유저가 쓴 질문게시물임다<b>(user.author_question.all)</b> <br> : {{user.author_question.all}}</div>
    <div>이 유저가 쓴 답변게시물임다<b>(user.author_answer.all)</b> <br> : {{user.author_answer.all}}</div>

    <div class="card my-3">

        <div class="card-body">

        <div>
            추천수 : <b>{{question.voter.all.count}}</b>
           <a href="{% url 'pybo:vote_question' question.id %}">추천하기</a>
        </div>
        <br>






        <!-- 사용자오류 표시 -->
        {% if messages %}
        <div class="alert alert-danger my-3" role="alert">
            {% for message in messages %}
            <strong>{{ message.tags }}</strong>
            <ul>
                <li>{{ message.message }}</li>
            </ul>
            {% endfor %}
        </div>
        {% endif %}



            <div class="card-text" style="white-space: pre-line;">{{ question.content|mark }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ question.create_date }}
                </div>
            </div>

        <a href="{% url 'pybo:comment_create_question' question.id %}"">코멘트입력</a>


        
    

        <ul>
            {% for comment in question.comment_set.all %}
                <li>{{ comment.content }} <b>-[{{comment.author}}]</b>

                    {% if request.user == comment.author %}
                
                        <a href="{% url 'pybo:comment_modify_question' comment.id %}">수정</a> 
                        / <a href="{% url 'pybo:comment_delete_question' comment.id %}">삭제</a>

                    {% endif %}

                    <i><a name="comment_{{comment.id}}">질문/코맨트앵커 : {{comment.id}}</a></i> 
                </li>
            {% endfor %}        
        </ul>


        </div>
    </div>


    




















    
    <!-- TEMPLATE에서 VARDUMP가능한가? -->
    {#% debug_object_dump request %#}
   

    
    {% if question.author == request.user %}
        <div class="my-3">
            <a href="{% url 'pybo:question_modify' question.id %}">수정하기</a>
             / 
            <a href="#" class='delete' data-uri="{% url 'pybo:question_delete' question.id %}">삭제하기</a>
        </div>
    {% endif %}
        
        
    


  
<h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}

    <a name=answer_{{answer.id}}>앵커 : answer_{{answer.id}}</a>
    <div class="card my-3">
        <div class="card-body">

            <div>
                추천수 : <b>{{answer.voter.count}}</b>
                <a href="{% url 'pybo:vote_answer' answer.id %}">추천하기</a>
            </div>
            <br>

            <div class="card-text">{{ answer.content|mark }}</div>

            <div>
                이 답변이 연결되어 있는 질문은? <b>(answer.question)</b> :<br>
                {{answer.question}} 
            </div>

            <div class="d-flex justify-content-end">
                {% if answer.modify_date %}
                <div class="badge badge-light p-2 text-left mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ answer.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ answer.author.username }}</div>
                    <div>{{ answer.create_date }}</div>
                </div>
            </div>
            {% if request.user == answer.author %}
            <div class="my-3">
                <a href="{% url 'pybo:answer_modify' answer.id  %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary "
                   data-uri="{% url 'pybo:answer_delete' answer.id  %}">삭제</a>
            </div>
            {% endif %}
            <a href="{% url 'pybo:comment_create_answer' answer.id %}">댓글달기</a>


            <ul>
            {% for comment in answer.comment_set.all %}
                
                <li>{{comment.content}} 

                    <a href="{% url 'pybo:comment_modify_answer' comment.id%}">수정</a>
                    / 
                    <a href="{% url 'pybo:comment_delete_answer' comment.id %}">삭제</a>
                    <span><i><a name="comment_{{comment.id}}">답변/코맨트앵커 : {{comment.id}}</a></i></span>
                </li>

            {% endfor %}
            </ul>                
            
        </div>
    </div>
    {% endfor %}

        

    
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        
        {% if form.errors %}
            {% for field in form %}
                {% if field.errors %}
                    ERROR.. >>>>>{{field.errors}}
                {% endif %}
            {% endfor %}
        {% endif %}
            

        <div class="form-group">
            <textarea 
            {% if not user.is_authenticated %} disabled {% endif %} 
            name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>

    <br>

    이 질문이 가지고 있는 답변 아이들 : 
    {{question.answer_set.all}}

















</div>
{% endblock content %}



{% block script %}
<script>
    $(document).ready(function () {
        $(".delete").on('click', function () {
            if (confirm("정말로 삭제하시겠습니까?")) {
                location.href = $(this).data('uri');
            }
        });
    });

    
</script>
{% endblock %}


{% if messages %}
{% for message in messages %}
{{ message.tags }}
{{ message.message }}
{% endfor %}
{% endif %}

templates/pybo/question_form.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
	<h5 class="my-3 border-bottom pb-2">질문등록</h5>
	<form method="post" class="post-form my-3">
		{% csrf_token %}

		
		
		{% if form.errors %}
			{% for field in form %}
				{% if field.errors %}
					<strong>field.label</strong>
					{{field.errors}}
				{% endif %}
			{% endfor %}
		{% endif %}



ghood:
{{ messages }}

{% if messages %}
<ul class="messages">
	{% for message in messages %}
	<li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
		{% endfor %}
</ul>
{% endif %}




<!-- message -->

{% for error in form.non_field_errors %}
<!-- 넌필드 오류를 출력한다. -->
<div class="alert alert-danger">
	<strong>{{ error }}</strong>
</div>
{% endfor %}



	{{ form.as_p }}

		<button type="submit" class="btn btn-primary">저장하기</button>
	</form>
</div>





{% endblock %}

templates/pybo/redirect.html
im redirect!

templates/pybo/todo_create_form.html
<form action="" method="POST">
	{% csrf_token %}

	THISIS TODO_FORM..WORKS?
	
	
	{{form.as_p}}
	<input type="submit" value="전송">


	
	{% for todo in todos %}
		<h5>{{todo.title}}</h5>
	{% endfor %}
		

</form>