lg/urls.py
from django.urls import path, reverse_lazy

from . import views


app_name = "lg"


urlpatterns = [


	path('', views.index, name="index" ),

	path('2/', views.index2, name="index2" ),
	path('3/', views.index3, name="index3" ),


	path('campaign/', views.campaign_view, name="campaign_view" ),






	path("api/campaign_list/", views.campaign_list, name="campaign_list"),

	path("api/select_list/<str:type>", views.select_list, name="select_list"),
	#path("api/select_list/<str:type>", views.select_list.as_view(), name="select_list"),



	path('home/', views.HomeView.as_view(), name="home" ),

	path("api/todo/list", views.ApiTodoLV.as_view(), name="list"),




]

lg/.bk/views/views_404_list.py
from django.core import serializers
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from django.http import JsonResponse, HttpResponse
from django.core.serializers.json import DjangoJSONEncoder
from django.db import connection

from util import *

from .models import Campaign,Category,Channel
from django.db.models import Q

import json




def index(request):
	pr("hello LG indexview")
	return render(request, 'lg/index.html', {})


def campaign_view(request):
	pr("hello campgin_view")
	return render(request, 'lg/campaign_view.html', {})




#DEBUG
def index2(request):
	pr("hello LG indexview22")
	return render(request, 'lg/index2.html', {})






def campaign_list(request):

	channel = request.GET.get('channel', "")
	category = request.GET.get('category', "")
	pr("lol channel : ")
	pr(channel)
	pr("lol cate! : ")
	pr(category)


	queryset = Campaign.objects.values('title', 'subtitle','channel', 'category',
										'img_path','created_time').order_by('-created_time')


	allowed_filters = ['category[]','channel[]']

	for filter_array_title in allowed_filters:

		filter_title = getArrayName(filter_array_title)

		pr("filter_title")
		pr(filter_title)

		if len(filter_title):

			#pr("i can check category HEAD!")
			q_objects = Q()
			for item in request.GET.getlist(filter_array_title):
				#pr("i can check INNER CATEGORY")

				q_objects |= Q(**{filter_title : item})
				#q_objects.add(Q(category = cat),q_objects.OR)

			queryset = queryset.filter(q_objects)

	#pr("QOBJECT : ")
	#pr(q_objects)


	data = json.dumps(list(queryset[:5]), cls=DjangoJSONEncoder)
	#data = json.dumps(list(queryset), cls=DjangoJSONEncoder)


	pr(data)

	pr("length")
	pr(queryset.count())

	pr("sql :::::::::::::")
	pr(connection.queries)


	#return JsonResponse(data, safe=False)
	return HttpResponse(data, content_type="application/json")











from django import http
from django.http import Http404
from django.apps import apps
from django.shortcuts import get_list_or_404,get_object_or_404





from django.core.exceptions import ObjectDoesNotExist












def get_list(request,type):

	allowed_filters = ['category','channel']

	if type in allowed_filters:

		pr("type in array!")

		Model = apps.get_model('lg', type)
		queryset = Model.objects.values('id','eng_name','kor_name')

		pr(queryset)
		data = json.dumps(list(queryset), cls=DjangoJSONEncoder)
		return HttpResponse( data, content_type="application/json")

	else:
		pr("type not array!")
		raise Http404("hello-AJAX ONLY VIEW")












def get_list_404(request,type):

	Model = apps.get_model('lg', type)

	# queryset = get_list_or_404(Model.objects.values('id','eng_name','kor_name'))
	queryset = Model.objects.values('id','eng_name','kor_name')



	# queryset = Model.objects.values('id','eng_name','kor_name')
	# pr("-------")
	# pr(my_objects)

	pr(queryset)

	data = json.dumps(list(queryset), cls=DjangoJSONEncoder)

	return HttpResponse( data, content_type="application/json")





















































from lg.models import Todo

class HomeView(TemplateView):
	template_name = 'lg/home.html'


class ApiTodoLV(ListView):
	model = Todo

	# def get(self,request,*args,**kwargs):
	#     tmpList=[
	# 			{'id': 1,'name': 'DJ김석훈', 'todo': 'Django 와 Vue.js 연동 프로그램을 만들고 있습니다.'},
	# 			{'id': 2,'name': 'DJ홍길동', 'todo': '이름을 안쓰면 홍길동으로 나와요...'},
	# 			{'id': 3,'name': 'DJ이순신', 'todo': '신에게는 아직 열두 척의 배가 있사옵니다.'},
	# 			{'id': 4,'name': 'DJ성춘향', 'todo': '그네 타기'},
	# 	]
	#	return JsonResponse(data=tmpList, safe=False)

	def render_to_response(self, context, **response_kwargs):
		todoList = list(context['object_list'].values())
		return JsonResponse(data=todoList, safe=False)

lg/.bk/views/views_for_cbv.py
from django.core import serializers
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from django.http import JsonResponse, HttpResponse
from django.core.serializers.json import DjangoJSONEncoder
from django.db import connection

from util import *

from .models import Campaign,Category,Channel
from django.db.models import Q

import json




def index(request):
	pr("hello LG indexview")
	return render(request, 'lg/index.html', {})


def campaign_view(request):
	pr("hello campgin_view")
	return render(request, 'lg/campaign_view.html', {})




#DEBUG
def index2(request):
	pr("hello LG indexview22")
	return render(request, 'lg/index2.html', {})






def campaign_list(request):

	channel = request.GET.get('channel', "")
	category = request.GET.get('category', "")
	pr("lol channel : ")
	pr(channel)
	pr("lol cate! : ")
	pr(category)


	queryset = Campaign.objects.values('title', 'subtitle','channel', 'category',
										'img_path','created_time').order_by('-created_time')


	allowed_filters = ['category[]','channel[]']

	for filter_array_title in allowed_filters:

		filter_title = getArrayName(filter_array_title)

		pr("filter_title")
		pr(filter_title)

		if len(filter_title):

			#pr("i can check category HEAD!")
			q_objects = Q()
			for item in request.GET.getlist(filter_array_title):
				#pr("i can check INNER CATEGORY")

				q_objects |= Q(**{filter_title : item})
				#q_objects.add(Q(category = cat),q_objects.OR)

			queryset = queryset.filter(q_objects)

	#pr("QOBJECT : ")
	#pr(q_objects)


	data = json.dumps(list(queryset[:5]), cls=DjangoJSONEncoder)
	#data = json.dumps(list(queryset), cls=DjangoJSONEncoder)


	pr(data)

	pr("length")
	pr(queryset.count())

	pr("sql :::::::::::::")
	pr(connection.queries)


	#return JsonResponse(data, safe=False)
	return HttpResponse(data, content_type="application/json")










from django.views.generic.list import ListView
from django.views import generic
from django.core import serializers
from django import http


class AJAXListMixin(object):

		#def dispatch(self, request, *args, **kwargs):
			#if not request.is_ajax():
				# raise http.Http404("hello-AJAX ONLY VIEW")
			#return super(AJAXListMixin, self).dispatch(request, *args, **kwargs)

		def get_queryset(self):
			return (
				super(AJAXListMixin, self)
				#.get_queryset().filter(eng_name='living')
				.get_queryset().all()
			)


		def get(self, request, *args, **kwargs):
			pr("request : ", self.get_queryset())
			pr("kwargs2", kwargs)
			return http.HttpResponse(serializers.serialize('json', self.get_queryset()))




class get_list(AJAXListMixin, generic.ListView):
	model = Category














'''
def get_list(request,type):
	#pr("getlist works")
	#pr(Category)
	queryset = Category.objects.all()
	pr(queryset)
	data = json.dumps(list(queryset), cls=DjangoJSONEncoder)
	return HttpResponse( data, content_type="application/json")
'''









































from lg.models import Todo

class HomeView(TemplateView):
	template_name = 'lg/home.html'


class ApiTodoLV(ListView):
	model = Todo

	# def get(self,request,*args,**kwargs):
	#     tmpList=[
	# 			{'id': 1,'name': 'DJ김석훈', 'todo': 'Django 와 Vue.js 연동 프로그램을 만들고 있습니다.'},
	# 			{'id': 2,'name': 'DJ홍길동', 'todo': '이름을 안쓰면 홍길동으로 나와요...'},
	# 			{'id': 3,'name': 'DJ이순신', 'todo': '신에게는 아직 열두 척의 배가 있사옵니다.'},
	# 			{'id': 4,'name': 'DJ성춘향', 'todo': '그네 타기'},
	# 	]
	#	return JsonResponse(data=tmpList, safe=False)

	def render_to_response(self, context, **response_kwargs):
		todoList = list(context['object_list'].values())
		return JsonResponse(data=todoList, safe=False)

lg/.bk/views/views_for_def.py
from django.core import serializers
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from django.http import JsonResponse, HttpResponse
from django.core.serializers.json import DjangoJSONEncoder
from django.db import connection

from util import *

from .models import Campaign,Category,Channel
from django.db.models import Q

import json




def index(request):
	p("hello LG indexview")
	return render(request, 'lg/index.html', {})


def campaign_view(request):
	p("hello campgin_view")
	return render(request, 'lg/campaign_view.html', {})




#DEBUG
def index2(request):
	p("hello LG indexview22")
	return render(request, 'lg/index2.html', {})






def campaign_list(request):

	channel = request.GET.get('channel', "")
	category = request.GET.get('category', "")
	p("lol channel : ")
	p(channel)
	p("lol cate! : ")
	p(category)


	queryset = Campaign.objects.values('title', 'subtitle','channel', 'category',
										'img_path','created_time').order_by('-created_time')


	allowed_filters = ['category[]','channel[]']

	for filter_array_title in allowed_filters:

		filter_title = getArrayName(filter_array_title)

		p("filter_title")
		p(filter_title)

		if len(filter_title):

			#p("i can check category HEAD!")
			q_objects = Q()
			for item in request.GET.getlist(filter_array_title):
				#p("i can check INNER CATEGORY")

				q_objects |= Q(**{filter_title : item})
				#q_objects.add(Q(category = cat),q_objects.OR)

			queryset = queryset.filter(q_objects)

	#p("QOBJECT : ")
	#p(q_objects)


	data = json.dumps(list(queryset[:5]), cls=DjangoJSONEncoder)
	#data = json.dumps(list(queryset), cls=DjangoJSONEncoder)


	p(data)

	p("length")
	p(queryset.count())

	p("sql :::::::::::::")
	p(connection.queries)


	#return JsonResponse(data, safe=False)
	return HttpResponse(data, content_type="application/json")





def get_list(request,type):
	#p("getlist works")
	#p(Category)

	queryset = Category.objects.values('id','eng_name','kor_name')

	p(queryset)

	data = json.dumps(list(queryset), cls=DjangoJSONEncoder)

	return HttpResponse( data, content_type="application/json")























from lg.models import Todo

class HomeView(TemplateView):
	template_name = 'lg/home.html'


class ApiTodoLV(ListView):
	model = Todo

	# def get(self,request,*args,**kwargs):
	#     tmpList=[
	# 			{'id': 1,'name': 'DJ김석훈', 'todo': 'Django 와 Vue.js 연동 프로그램을 만들고 있습니다.'},
	# 			{'id': 2,'name': 'DJ홍길동', 'todo': '이름을 안쓰면 홍길동으로 나와요...'},
	# 			{'id': 3,'name': 'DJ이순신', 'todo': '신에게는 아직 열두 척의 배가 있사옵니다.'},
	# 			{'id': 4,'name': 'DJ성춘향', 'todo': '그네 타기'},
	# 	]
	#	return JsonResponse(data=tmpList, safe=False)

	def render_to_response(self, context, **response_kwargs):
		todoList = list(context['object_list'].values())
		return JsonResponse(data=todoList, safe=False)

lg/.bk/views/views_with_perfcheck.py
from django.core import serializers
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from django.http import JsonResponse, HttpResponse
from django.core.serializers.json import DjangoJSONEncoder
from django.db import connection

from util import *

from .models import Campaign,Category,Channel
from django.db.models import Q

import json




def index(request):
	pr("hello LG indexview")
	return render(request, 'lg/index.html', {})


def campaign_view(request):
	pr("hello campgin_view")
	return render(request, 'lg/campaign_view.html', {})




#DEBUG
def index2(request):
	pr("hello LG indexview22")
	return render(request, 'lg/index2.html', {})
















@query_debugger
def campaign_list(request):

	# channel = request.GET.get('channel', "")
	# category = request.GET.get('category', "")





	queryset = Campaign.objects.select_related('category').all()


	# queryset = Campaign.objects.select_related('Category').values('title', 'subtitle','channel', 'category__eng_name','img_path','created_time').order_by('-created_time')

	# queryset = Campaign.objects.values('title', 'subtitle','channel', 'category__eng_name','img_path','created_time').order_by('-created_time')


	allowed_filters = ['category[]','channel[]']

	for filter_array_title in allowed_filters:

		filter_title = getArrayName(filter_array_title)

		# pr("filter_title",filter_title)

		if len(filter_title):

			#pr("i can check category HEAD!")
			q_objects = Q()
			for item in request.GET.getlist(filter_array_title):
				#pr("i can check INNER CATEGORY")

				q_objects |= Q(**{filter_title : item})
				#q_objects.add(Q(category = cat),q_objects.OR)

			queryset = queryset.filter(q_objects)

	#pr("QOBJECT : ")
	#pr(q_objects)




	# pr(queryset.title)

	camps = []
	for camp in queryset[:10]:  # queryset 평가
		camps.append({
			'id': camp.id,
			'name': camp.title,
			'category_title': camp.category.kor_name
			}
		)

		"""
		< 1)existing list
		camps.. append(
			2) existing obj..
		)
		 """
	pr(camps)




	#data = json.dumps(list(queryset), cls=DjangoJSONEncoder)
	# data = json.dumps(list(queryset[:5]), cls=DjangoJSONEncoder)





	# pr("length")
	# pr(queryset.count())

	pr("sql :::::::::::::")
	pr(connection.queries)


	#return JsonResponse(data, safe=False)
	return HttpResponse(data, content_type="application/json")











from django import http
from django.http import Http404
from django.apps import apps
from django.shortcuts import get_list_or_404,get_object_or_404





from django.core.exceptions import ObjectDoesNotExist












def get_list(request,type):

	allowed_filters = ['category','channel']

	if type in allowed_filters:

		Model = apps.get_model('lg', type)
		queryset = Model.objects.all()
		data = serializers.serialize('json', queryset)

		return HttpResponse( data, content_type="application/json")

	else:
		raise Http404("잘못된 접근입니다")





























































from lg.models import Todo

class HomeView(TemplateView):
	template_name = 'lg/home.html'


class ApiTodoLV(ListView):
	model = Todo

	# def get(self,request,*args,**kwargs):
	#     tmpList=[
	# 			{'id': 1,'name': 'DJ김석훈', 'todo': 'Django 와 Vue.js 연동 프로그램을 만들고 있습니다.'},
	# 			{'id': 2,'name': 'DJ홍길동', 'todo': '이름을 안쓰면 홍길동으로 나와요...'},
	# 			{'id': 3,'name': 'DJ이순신', 'todo': '신에게는 아직 열두 척의 배가 있사옵니다.'},
	# 			{'id': 4,'name': 'DJ성춘향', 'todo': '그네 타기'},
	# 	]
	#	return JsonResponse(data=tmpList, safe=False)

	def render_to_response(self, context, **response_kwargs):
		todoList = list(context['object_list'].values())
		return JsonResponse(data=todoList, safe=False)

templates/lg/.bk/index/1016_152155 @before_infinite@ index.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}

<body>
   <style>
      html {
         line-height: 1.15;
         font-size: 1rem;
         font-family: 'Noto Sans KR';
      }




      .wrapper {
         width: 100%;
         height: 100%;
      }




      .container {
         margin: 0 auto;

         max-width: 1400px;
         min-width: 1400px;

         border: 2px solid red;
         background: coral;
      }








      /*
이걸 1200으로 하면 반갈죽을 포기해야한다..맞나?
 */



      .card_list_box {

         /* background: gold; */
         /* min-width: 1400px; */
         /* width: 100%; */
         /* VAR-READY */

         display: flex;
         flex-direction: row;
         flex-wrap: wrap;
         justify-content: space-between;

      }


      .card_list_box:after {
         content: "";
         flex-grow: 1;
      }



      .card {
         background: green;
         border: 1px solid purple;

         width: 224px;
         margin-right: 10.4px;


         margin-bottom: 10px;
         /* height: 150px; */
         height: 285px;

      }

      .card:nth-child(6n) {
         margin-right: 0;
         background: blue;
      }

      .card a {
         width: 100%;
         height: 100%;
         background: red;
      }


      img.card_img {
         width: 100%;
      }

      .card_title {
         padding: 10px 0;
      }





      /* 미리 준비.. 1200으로 */
      @media screen and (max-width: 1400px) {
         .container {

            min-width: 940px;
            max-width: 940px;
            background: cyan;

         }

         .card {
            width: 180px;
            margin-right: 8.2px;
         }

         .card:nth-child(6n) {
            margin-right: 8.2px;
            background: yellow;
         }

         .card:nth-child(5n) {
            margin-right: 0;
            background: blue;
         }



      }







      @media screen and (max-width: 500px) {

         .container {
            min-width: 100%;
            max-width: 100%;
            background: yellow;

         }

         .card_list_box {
            padding: 0 5px;
         }

         .card {
            width: 50%;
            height: inherit;
            padding: 5px 5px 15px 5px;
         }

         .card,
         .card:nth-child(5n),
         .card:nth-child(6n) {
            margin-right: inherit;
         }

      }


      .filter_box{
         display: inline-flex;
      }

      .filter_box label{
         vertical-align: middle;
         line-height: 38px;
      }

      .filter_checkbox{
         height: 40px;
         user-select: none;
         margin-left: 30px;
         margin-right: 5px;
      }
   </style>
   <div class="wrapper">
      <div class="container">top</div>

      <div class="container">banner /
         <a href="http://127.0.0.1:8000/campaign/">캠패인보기</a>
      </div>


      <div class="container">


         <div class="filter_box">


         {% for category in category_list %}
            <input type="checkbox"
            {% if category.eng_name in request.GET.category %}checked="checked"{% endif %}
            id="ca_{{category}}" name="{{category}}" value="{{category}}" class="filter_checkbox" data-type="category">
            <label for="ca_{{category}}">{{category.kor_name}}</label><br>
         {% endfor %}
         </div>
         <hr>
         <div class="filter_box">
            {% for channel in channel_list %}
               <input type="checkbox"
               {% if channel.eng_name in request.GET.channel %}checked="checked"{% endif %}
               id="ca_{{channel}}" name="{{channel}}" value="{{channel}}" class="filter_checkbox" data-type="channel">
               <label for="ca_{{channel}}">{{channel.kor_name}}</label><br>
            {% endfor %}
         </div>







         <!-- <div class="filter_box">

            <input type="checkbox" id="ca_cafe" name="cafe" value="cafe" class="filter_checkbox" data-type="category">
            <label for="ca_cafe">cafe</label><br>

            <input type="checkbox" id="ca_living" name="living" value="living" class="filter_checkbox" data-type="category">
            <label for="ca_living">living</label><br>

            <input type="checkbox" id="ca_tech" name="tech" value="tech" class="filter_checkbox" data-type="category">
            <label for="ca_tech">tech</label><br>

            <input type="checkbox" id="ca_food" name="food" value="food" class="filter_checkbox" data-type="category">
            <label for="ca_food">food</label><br>

            <input type="checkbox" id="ca_beauty" name="beauty" value="beauty" class="filter_checkbox" data-type="category">
            <label for="ca_beauty">beauty</label><br>

            <input type="checkbox" id="ca_culture" name="culture" value="culture" class="filter_checkbox" data-type="category">
            <label for="ca_culture">culture</label><br>
         </div> -->

         <!-- <hr> -->

         <!-- <div class="filter_box">

            <input type="checkbox" id="ch_blog" name="blog" value="blog" class="filter_checkbox" data-type="channel">
            <label for="ch_blog">Blog</label><br>

            <input type="checkbox" id="ch_instagram" name="instagram" value="instagram" class="filter_checkbox" data-type="channel">
            <label for="ch_instagram">Instagram</label><br>

            <input type="checkbox" id="ch_youtube" name="youtube" value="youtube" class="filter_checkbox" data-type="channel">
            <label for="ch_youtube">Youtube</label><br>

            <input type="checkbox" id="ch_cafe" name="cafe" value="cafe" class="filter_checkbox" data-type="channel">
            <label for="ch_cafe">Cafe</label><br>

            <input type="checkbox" id="ch_shop" name="shop" value="shop" class="filter_checkbox" data-type="channel">
            <label for="ch_shop">Shop</label><br>

         </div> -->




      </div>



      <div class="container">
         <!-- <a href="{% url 'lg:campaign_view' %}">TESTER</a> -->
         <!-- <a href="{% url 'lg:campaign_view' %}">TESTER</a> -->
         <ul class="card_list_box"></ul>
      </div>


      <div class="test_list_box"></div>

   </div>




</body>
{% endblock %}
{% block script %}
<script>














$('.filter_checkbox').change(function(e){



   var param_type = $(this).data('type')
   var checked_val = $(this).val()
   var status = this.checked
   const url_params = new URLSearchParams(window.location.search);
   var new_url_var


   if(status == true){

      // key= 있는지 확인 후 추가
        if( !url_params.has(param_type) ){
         url_params.append(param_type,'')
      }

      //현재 선택한 값을 넣기 위해 url_params를 array화
      var cur_params_array = url_params.get(param_type).split(",");


      // split으로 생겨난 빈칸 삭제
      var cur_params_array = cur_params_array.filter(function (e) {
         return e != "";
      });



      //현재 선택한 값을 array에 삽입
      cur_params_array.push(checked_val);


      // 혹시 모를 중복삭제
      cur_params_array = cur_params_array.filter(function(item, pos) {
          return cur_params_array.indexOf(item) == pos;
      })

      //url에 넣기위해 array를 comma-separate로 변환
      var new_params = cur_params_array.join(',');

      // urlSearch에 장착
      url_params.set(param_type, new_params);

      new_url_var = "?"+ decodeURIComponent(url_params)


   } else if (status == false){


      var cur_params_array = url_params.get(param_type).split(",");
      var new_params_array = removeItem(cur_params_array, checked_val);
      var new_params = new_params_array.join(',');


      if(cur_params_array.length){

         // value= 값이 아직 남아있으므로 value= 유지
         url_params.set(param_type, new_params);
         new_url_var = "?"+ decodeURIComponent(url_params)

      } else {

         // value=값이 없으므로 value= 까지 삭제
         url_params.delete(param_type);
         new_url_var = "?"+ decodeURIComponent(url_params)

            //param이 전부없으면 물음표까지 삭제
            var url_key_length = Array.from(url_params).length
            if(!url_key_length){
               new_url_var = "/"
            }

      }
   }


   // TODO ) B문제 때문에 추가함
   window.history.replaceState("", "", new_url_var )

   generateList()

})








setTimeout(function(){

   //console.log("lolcoms");/
   //$("#cafe").trigger('click')
   //$("#cafe").trigger('click')

}, 100);
















$( function() {

   generateList()


   inflist.init();

});


   var inflist = {

      param: {
         curPage: 1,
         pageListSize: 15,
      },

      init: function () {
         this.testData();
         this.checkScroll();
      },
      testData: function () {

         // this.setListItems("${firstData}"); // 첫 진입시 데이터 셋팅
         inflist.generateList()


      },

      checkScroll: function () {
         // 무한 스크롤
         $(window).scroll(function () {
            if ($(window).scrollTop() == $(document).height() - $(window).height()) {

               console.log('hello it works');
               //   this.param.curPage++; // 현재 페이지에서 +1 처리.
               //   this.testAjax(); //ajax 호출

               // inflist.testFunc();
               // console.log('but not works');

               inflist.param.curPage++;

               inflist.generateList()

            }
         });
      },
      generateList: function () {

         // ajax 자리임

         console.log('AJAX TEST WORKS');

         var urlParams = new URLSearchParams(window.location.search);
         // url param 체크 후 있을경우 array화 해줌
         var filter_space = {};
         allowed_filters = ['category','channel']
         allowed_filters.forEach(function(filter){
            if(urlParams.get(filter)){
               filter_space[filter] = urlParams.get(filter).split(',')
            }
         })

         $.ajax({
            type: 'GET',
            url: "api/campaign_list/",
            //data: { csrfmiddlewaretoken: window.CSRF_TOKEN, category: "cafe" },
            data: {
               csrfmiddlewaretoken: window.CSRF_TOKEN,
               //category: ["cafe","living","food"],
               //category: ["cafe"],
               //category: [category],
               //category: [],
               //channel:["BLOG","INSTA"]
               //channel:[channel],
               category: filter_space['category'],
               channel:filter_space['channel'],
            },


            success: function (res) {

               var div_list = "";

               $.each(res, function (i, item) {


                  var div = `
                           <li class='card'>
                              <a href="{% url 'lg:campaign_view' %}">
                                 <div class='card_img_box'>
                                    <img class='card_img' src="static/img/${res[i].img_path}" alt="">
                                 </div>
                                 <div class='card_title'>${res[i].channel__eng_name} - ${res[i].title} ${res[i].category__eng_name}</div>
                                 <div class='card_subtitle'>${res[i].subtitle} <br> ${res[i].created_time}</div>
                              </a>
                           </li>
                           `
                  div_list += div;
               });

               // $('.card_list_box').empty().append(div_list)
               $('.card_list_box').append(div_list)


            }
         })







      }



   }














































function generateList(){

   // console.log('GENERATE WORKS');


   var urlParams = new URLSearchParams(window.location.search);
   // url param 체크 후 있을경우 array화 해줌
   var filter_space = {};
   allowed_filters = ['category','channel']
   allowed_filters.forEach(function(filter){
      if(urlParams.get(filter)){
         filter_space[filter] = urlParams.get(filter).split(',')
      }
   })

   // console.log("filter_space['category'] : ", filter_space['category'])
   // console.log("filter_space['channel'] : ", filter_space['channel'])



   $.ajax({
      type: 'GET',
      url: "api/campaign_list/",
      //data: { csrfmiddlewaretoken: window.CSRF_TOKEN, category: "cafe" },
      data: {
         csrfmiddlewaretoken: window.CSRF_TOKEN,
         //category: ["cafe","living","food"],
         //category: ["cafe"],
         //category: [category],
         //category: [],
         //channel:["BLOG","INSTA"]
         //channel:[channel],
         category: filter_space['category'],
         channel:filter_space['channel'],
      },


      success: function (res) {

         var div_list = "";

         $.each(res, function (i, item) {


            var div = `
                     <li class='card'>
                        <a href="{% url 'lg:campaign_view' %}">
                           <div class='card_img_box'>
                              <img class='card_img' src="static/img/${res[i].img_path}" alt="">
                           </div>
                           <div class='card_title'>${res[i].channel__eng_name} - ${res[i].title} ${res[i].category__eng_name}</div>
                           <div class='card_subtitle'>${res[i].subtitle} <br> ${res[i].created_time}</div>
                        </a>
                     </li>
                     `
            div_list += div;
         });
         $('.card_list_box').empty().append(div_list)


      }
   })
}




function removeItem(arr) {
       var what, a = arguments, L = a.length, ax;
       while (L > 1 && arr.length) {
           what = a[--L];
           while ((ax= arr.indexOf(what)) !== -1) {
               arr.splice(ax, 1);
           }
       }
       return arr;
   }



</script>
{% endblock script %}