common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

#  as로 닉네임을 정해서. auth_views 로 밑에서 사용한다.


app_name = 'common'

urlpatterns = [
    path("login/",
         auth_views.LoginView.as_view(
                template_name="common/login.html",
                redirect_authenticated_user=True),
                name="login"),
    
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.signup, name="signup"),
]



# 아..template_name을 원래 view에서 해주는데, 여기서 간단하게 가능하다.
# > urls는 function조립기야.

# 이때 그냥하면 LoginView에서 template를 확인하고 없으면 에러를 발생시킨다.

lg/urls.py
from django.urls import path, reverse_lazy

from . import views


app_name = "lg"


urlpatterns = [


	path('', views.index, name="index" ),

	path('2/', views.index2, name="index2" ),
	path('3/', views.index3, name="index3" ),


	path('campaign/', views.campaign_view, name="campaign_view" ),






	path("api/campaign_list/", views.campaign_list, name="campaign_list"),

	path("api/select_list/<str:type>", views.select_list, name="select_list"),
	#path("api/select_list/<str:type>", views.select_list.as_view(), name="select_list"),



	path('home/', views.HomeView.as_view(), name="home" ),

	path("api/todo/list", views.ApiTodoLV.as_view(), name="list"),




]

pybo/urls.py
from django.urls import path, reverse_lazy

from .views import base_views, question_views, answer_views, comment_views, vote_views, q_views

from django.views.generic import CreateView
from pybo.models import Question, Todo






app_name = "pybo"

urlpatterns = [



    path('q_list/', q_views.q_list,name="q_list" ),




    path('api/', base_views.apiOverview,name="api-overview" ),


    path('q-list/', base_views.questionList,name="question-list" ),
    path('q-detail/<str:pk>/', base_views.questionDetail,name="question-detail" ),

    path('q-create/', base_views.questionCreate,name="question-create" ),

    path('t-list/', base_views.todoList,name="todo-list" ),
    path('t-create/', base_views.todoCreate,name="todo-create" ),

    path('t-update/<str:pk>/', base_views.todoUpdate,name="todo-update" ),
    path('t-delete/<str:pk>/', base_views.todoDelete,name="todo-delete" ),















    # path("home/", CreateView.as_view(model=Todo, fields=['title'], success_url=reverse_lazy('home')), name="home"),

    path("hssome/", base_views.TodoCreateView.as_view(), name="home"),




















    path("", base_views.index, name='index'),
    path("<int:question_id>/", base_views.detail, name="detail"),

    path("question/create/", question_views.question_create, name="question_create"),
    path("question/modify/<int:question_id>/", question_views.question_modify, name="question_modify"),
    path("question/delete/<int:question_id>/", question_views.question_delete, name="question_delete"),

    path("answer/create/<int:question_id>/", answer_views.answer_create, name="answer_create"),
    path("answer/modify/<int:answer_id>/", answer_views.answer_modify, name="answer_modify"),
    path("answer/delete/<int:answer_id>/", answer_views.answer_delete, name="answer_delete"),

    path("comment/create/question/<int:question_id>/", comment_views.comment_create_question, name="comment_create_question"),
    path("comment/modify/question/<int:comment_id>/", comment_views.comment_modify_question, name="comment_modify_question"),
    path("comment/delete/question/<int:comment_id>/", comment_views.comment_delete_question, name="comment_delete_question"),
    path("comment/create/answer/<int:answer_id>", comment_views.comment_create_answer, name="comment_create_answer"),
    path("comment/modify/answer/<int:comment_id>", comment_views.comment_modify_answer, name="comment_modify_answer"),
    path("comment/delete/answer/<int:comment_id>", comment_views.comment_delete_answer, name="comment_delete_answer"),



    path("vote/question/<int:question_id>/", vote_views.vote_question, name="vote_question"),
    path("vote/answer/<int:answer_id>", vote_views.vote_answer, name="vote_answer"),



    path("about/", question_views.AboutView.as_view(), name="about"),





    path("hresponse//", question_views.hresponse_view, name="hresponse"),
    path("reverse/<int:question_id>", question_views.reverse_view, name="reverse"),
    path("resolve_url/<int:question_id>", question_views.resolveurl_view, name="resolveurl_view"),
    path("redirect_view/<int:question_id>", question_views.redirect_view, name="redirect_view"),
    path("reverse_lazy/<int:question_id>", question_views.reverselazy_view, name="reverselazy_view"),
    path("resol/<int:question_id>", question_views.resolve_view, name="resolve_view"),



]

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.shortcuts import render, get_object_or_404, redirect, reverse, resolve_url


from ..models import Question,Book,Store,Employee,Department

# from util import *


# def index(request):

# 	print("LIST WORKS")

# 	print("okay helloworld")
# 	print(Question.objects.filter(subject__contains="sO"))

# 	page = request.GET.get('page','1')
# 	question_list = Question.objects.order_by('-create_date')
# 	paginator = Paginator(question_list,20)
# 	page_obj = paginator.get_page(page)
# 	context = {'question_list':page_obj}

# 	return render(request,'pybo/question_list.html',context)






from django.db.models import Q, Count



import logging

logger = logging.getLogger('pybo')

print(">>>")
print(__name__)
# pybo는.. 로거명이다.
# 이걸로 logger.debug, logger.error, logger.warning

# 이 로거 객체는.. 이제 이걸로 info,warning,error,debug 메소드를 쓸 수 있다..!
'''
def index(request):

	# logger.info("INFO 레벨로 출력한다!")
	# logger.warning("warning 레벨로 출력한다!")
	# logger.error("error 레벨로 출력한다!")
	# logger.debug("debug 레벨로 출력한다!")
	
	page = request.GET.get('page',1)
	kw = request.GET.get('kw','')
	so = request.GET.get('so','recent')

	if so == "recommend":
		question_list = Question.objects.annotate(
			r_count = Count('voter'),
			cr_count = Count('voter'),
		).order_by('-r_count','-create_date').distinct()



	elif so == "question":
		question_list = Question.objects.annotate(
			q_count = Count('answer')
		).order_by('-q_count','-create_date').distict()
	else:
		question_list = Question.objects.order_by('-create_date')


	if kw:
		question_list = question_list.filter(
			Q(subject__icontains = kw) |
			Q(content__icontains = kw) |
			Q(author__username__icontains = kw) |
			Q(answer__author__username__icontains = kw)
		)


	paginator = Paginator(question_list,15)
	page_obj = paginator.get_page(page)

	context = {'question_list':page_obj, 'page':page,'kw':kw,'so':so}
	return render(request,'pybo/question_list.html',context)
'''











minusfunc = lambda a,b : a-b


def detail(request, question_id):

	print("hello im detail")
	question = get_object_or_404(Question, pk=question_id)
	context = {"question": question}

	print("--work--")

	# resolve_url은 reverse고.. reverse에서 args=[self.id] 를 간략화한 버전이다!
	# print( resolve_url('pybo:detail', question_id) )
	
	# print( resolve_url(question) )
	# print( redirect(question) )

	# 사실 resolve_url이 필요한건.. 맨 뒤 name이다.!


	return render(request, "pybo/question_detail.html", context)



from django.views.generic import CreateView
from pybo.models import Todo
from django.urls import reverse_lazy
from pybo.forms import TodoForm



from django.http import JsonResponse
from rest_framework.decorators import api_view
from rest_framework.response import Response
from ..serializers import QuestionSerializer, TodoSerializer 


@api_view(['GET'])
def apiOverview(request):
	api_urls = {'sucks':'sucks'}
	return Response(api_urls)
	

@api_view(['GET'])
def questionList(request):
	questions = Question.objects.all()
	serializer = QuestionSerializer(questions, many=True)
	return Response(serializer.data)
	
@api_view(['GET'])
def todoList(request):
	todos = Todo.objects.all()
	serializer = TodoSerializer(todos, many=True)
	return Response(serializer.data)



@api_view(['GET'])
def questionDetail(request,pk):
	questions = Question.objects.get(id=pk)
	serializer = QuestionSerializer(questions, many=False)
	return Response(serializer.data)

@api_view(['POST'])
#THIS only allow POST
def questionCreate(request):
	serializer = QuestionSerializer(data = request.data)
	if serializer.is_valid():
		serializer.save()
	return Response(serializer.data)




@api_view(['POST'])
def todoCreate(request):
	serializer = TodoSerializer(data = request.data)
	if serializer.is_valid():
		serializer.save()
	return Response(serializer.data)
	

@api_view(['POST'])
def todoUpdate(request, pk):
	todo = Todo.objects.get(id=pk)
	serializer = TodoSerializer(instance = todo, data = request.data)
	if serializer.is_valid():
		serializer.save()
	return Response(serializer.data)
	



@api_view(['DELETE'])
def todoDelete(request, pk):
	todo = Todo.objects.get(id=pk)
	todo.delete()
	return Response("your data is fucked! okay!")
	#ah.. Response는 아예 그 template를 만들어줌 











class TodoCreateView(CreateView):
	model = Todo
	# fields = '__all__'
	form_class = TodoForm
	success_url = reverse_lazy('pybo:home')

	# template_name = 'pybo/todo_former.html'
	template_name_suffix = '_create_form'

	def get_context_data(self,**kwargs):
		context = super(TodoCreateView,self).get_context_data(**kwargs)
		
		context['todos'] = Todo.objects.all()

		# 보면 context호출시 모든..todo가 호출되고 있다..!

		return context

	# def form_invalid(self, form):
	# 	print("invalid..stop!")

	def form_valid(self,form):
		print("valid.. proceed")
		return super().form_valid(form)


from django.http import HttpResponse
from django.views import View

class MyView(View):

    def get(self, request, *args, **kwargs):
        return HttpResponse('Hello, World! IM GET!')

    def POST(self, request, *args, **kwargs):
        return HttpResponse('Hello, World! IM POST!')

templates/base.html
{% load static %}

<html lang="ko">
	<head>
		 <meta charset="utf-8">
		 <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,shrink-to-fit=no,user-scalable=no">


		 <link rel="stylesheet" href="{% static 'css/fontawesome.all.min.css' %}">
		 <link rel="stylesheet" href="{% static 'css/open-iconic.min.css' %}">
		 <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
		 <link rel="stylesheet" href="{% static 'css/style.css' %}">

		 <!-- <title>LOGRIVAL</title> -->
		 <title>localhost</title>

	</head>






		{% block content %}

		{% endblock %}

		<script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'js/jquery.cookie.js' %}"></script>


		<script>


	var csrftoken = $.cookie('csrftoken');

	function csrfSafeMethod(method) {
		// these HTTP methods do not require CSRF protection
		return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
	}

	$.ajaxSetup({
		beforeSend: function(xhr, settings) {
			if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
					xhr.setRequestHeader("X-CSRFToken", csrftoken);
			}
		}
	});





		</script>

		{% block script %}


		{% endblock %}




		</html>

templates/bk_base.html
{% load static %}

<html lang="ko">
	<head>
		 <meta charset="utf-8">
		 <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		 <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
		 <link rel="stylesheet" href="{% static 'style.css' %}">



		 <title>localhost PYBO</title>
	</head>
	<style>
		.num{
			color:blue;
		}
		.current_num{
			color:red;
		}
		
		</style>
	<body>

		{% include 'navbar.html' %}



		{% block content %}
		{% endblock %}


<script src="{% static 'jquery.min.js' %}"></script>
<script src="{% static 'bootstrap.min.js' %}"></script>
			
		{% block script %}
		{% endblock %}

		
	</body>
</html>

<script>
	if ( window.history.replaceState ) {
	  window.history.replaceState( null, null, window.location.href );
	}
	</script>

	

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
	<a class="navbar-brand" href="{% url 'pybo:index' %}">PyboSS</a>
	<button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
		aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
		<ul class="navbar-nav">


			<li class="nav-item ">
				
				{% if user.is_authenticated %}
					welcome, {{ user.username }} / 
					<a href="{% url 'common:logout' %}">로그아웃</a>
				{% else %}
					<a href="{% url 'common:login' %}">로그인</a>
					 / <a href="{% url 'common:signup' %}">회원가입하기</a>
				{% endif %}
				


			</li>
			


		</ul>
	</div>
</nav>